version: "3.6"
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./logs/:/var/log/nginx/:rw
      - flashcard_build:/app/:ro
      - ./nginx/samplehtml/:/usr/share/nginx/samplehtml/:ro

volumes:
  static:
    flashcard_build:
