version: '3.6'
services:
   nginx:
     build:
      context: ./nginx
     ports:
       - "80:80"
     volumes:
       - static:/usr/src/app/static/:rw
       - ./logs/:/var/log/nginx/:rw
       - ./build/:/usr/share/nginx/html/:rw
       - ./nginx/samplehtml/:/usr/share/nginx/samplehtml/:ro



volumes:
  static:
  flashcard_volume:
