version: "3.6"
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - /opt/flashcards/logs/:/var/log/nginx/:rw
      - build:/app/:ro
      - ./nginx/samplehtml/:/usr/share/nginx/samplehtml/:ro

volumes:
   build:
